### ISSUE TITLE
meeting 12/1

### ISSUE THREAD

**Issue by BarbaraMcG** [Living-with-machines/TargetedSenseDisambiguation#109]
- [x] Time-sensitive approaches: update, paper sections? @kasparvonbeelen #88 #41 #104 
- [x] pipeline on all senses and words @kasparvonbeelen  @kasra-hosseini  #96 
- [x] Baselines and evaluation framework: update, paper sections? @mcollardanuy @fedenanni #7 #8 
- [x] Case studies @GiorgiatolfoBL @kasparvonbeelen 
- [x] Fine-tune BERT embeddings on OED quotations corpus? @kasra-hosseini 
- [x] Q: do we need a WSD SOTA?
