### ISSUE TITLE
meeting on 2/11

### ISSUE THREAD

**Issue by BarbaraMcG** [Living-with-machines/TargetedSenseDisambiguation#32]
- [x] finalise task description https://github.com/Living-with-machines/HistoricalDictionaryExpansion/issues/28
- [x] decide on reading group assignments and dates https://github.com/Living-with-machines/HistoricalDictionaryExpansion/issues/6
- [x] decide on first set of experiments https://github.com/Living-with-machines/HistoricalDictionaryExpansion/issues/13
- [x] Meetings: Tuesdays 11.30-12 for catch-ups and 12-12.30 for reading group? https://github.com/Living-with-machines/HistoricalDictionaryExpansion/issues/15
- [x] actions
