### ISSUE TITLE
Meeting 24/11

### ISSUE THREAD

**Issue by BarbaraMcG** [Living-with-machines/TargetedSenseDisambiguation#67]
- [x] update on baseline models https://github.com/Living-with-machines/HistoricalDictionaryExpansion/issues/8
- [x] update on sense embeddings experiment https://github.com/Living-with-machines/HistoricalDictionaryExpansion/issues/41
- [x] update for Mia https://github.com/Living-with-machines/HistoricalDictionaryExpansion/issues/61
- [x] split paper sections https://github.com/Living-with-machines/HistoricalDictionaryExpansion/issues/42: this moves to next time
- [x] next tickets
