### ISSUE TITLE
meeting 1/12

### ISSUE THREAD

**Issue by BarbaraMcG** [Living-with-machines/TargetedSenseDisambiguation#68]
- [x] update on baselines and table for paper #41 and #8 
- [x] evaluation approach and metrics #7 
- [x] split paper sections https://github.com/Living-with-machines/HistoricalDictionaryExpansion/issues/42 #56 
- [x] Turing NLP reading group presentation #55
