### ISSUE TITLE
meeting 8/12

### ISSUE THREAD

**Issue by BarbaraMcG** [Living-with-machines/TargetedSenseDisambiguation#69]
- [x] (5 minutes) workload and timelines 
- [x] (5 minutes) architecture: start adding names to boxes #13 
- [x] (5 minutes) updates on experiments:

>  @kasparvonbeelen  #70 

> @mcollardanuy #77 

>  @GiorgiatolfoBL #78 

- [x] (10) new tickets
- [x] (2 minutes) update for Mia https://github.com/Living-with-machines/HistoricalDictionaryExpansion/issues/61
- [x] (2 minutes) Turing NLP reading group presentation #55 
- [x] (1 minute) next meetings and Christmas break
