### ISSUE TITLE
meeting 15/12

### ISSUE THREAD

**Issue by BarbaraMcG** [Living-with-machines/TargetedSenseDisambiguation#87]
- [x] update on new words #78 @GiorgiatolfoBL 
- [x] update on training/test split #7 #89 @fedenanni 
- [x] update on baselines #8
- [x] architecture #13 and move tickets in https://github.com/Living-with-machines/HistoricalDictionaryExpansion/projects/2
