### ISSUE TITLE
meeting 5/1

### ISSUE THREAD

**Issue by BarbaraMcG** [Living-with-machines/TargetedSenseDisambiguation#94]
- [x] (10 minutes) parallelisation @kasra-hosseini 
- [x] (10 minutes) how to prune the OED-thesaurus branches @kasparvonbeelen 
- [x] (10 minutes) training/test split @fedenanni with the aim to unblock the next steps #89 
- [x] (5 minutes) how/when to work together from now until submission @BarbaraMcG 
- [x] (5 minutes) paper draft: start adding names to sections #56 @BarbaraMcG https://www.overleaf.com/project/5faa8416f7428e7279ee6d82
- [ ] (2 minutes) author credits #10 @BarbaraMcG
